import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const adminHtml = readFileSync(new URL('../admin.html', import.meta.url), 'utf8');
const workerJs = readFileSync(new URL('../worker/index.js', import.meta.url), 'utf8');

assert.doesNotMatch(adminHtml, /週管理總覽|weekly-overview|weekly-current-count|weekly-target-count|weekly-8e-ratio|weekly-ring-ratio|renderWeeklyOverview/, 'admin dashboard should not duplicate top summary cards with a weekly overview section');
assert.match(adminHtml, /RM 組動能逐週管理/, 'admin dashboard should include the RM group weekly momentum matrix');
assert.match(adminHtml, /行銷人員管理雷達/, 'admin radar section should use the clearer marketing staff title');
assert.match(adminHtml, /radar-scope/, 'admin radar should expose a personal scope switch');
assert.match(adminHtml, /data-radar-scope="week"/, 'admin radar should support a current-week personal view');
assert.match(adminHtml, /data-radar-scope="fourWeeks"/, 'admin radar should support a recent four-week personal view');
assert.match(adminHtml, /data-radar-scope="all"/, 'admin radar should preserve an all-time personal view');
assert.match(adminHtml, /let radarScope = 'week'/, 'admin radar should default to the current-week personal view');
assert.match(adminHtml, /renderRadar\(getScopedRadarData\(\)/, 'admin radar should render from scoped personal data rather than only the dashboard range');
assert.match(adminHtml, /本週會議/, 'admin radar should show whether a person submitted a weekly meeting');
assert.doesNotMatch(adminHtml, />業務多樣性<|bizLabel/, 'admin radar should not show business diversity as a staff-level column');
assert.match(adminHtml, /近 10 工作日拜訪趨勢/, 'admin dashboard should preserve the recent 10 workday trend');
assert.match(adminHtml, /renderGroupWeeklyMatrix/, 'admin dashboard should render the group weekly matrix');
assert.match(adminHtml, /GROUP_TARGETS/, 'admin dashboard should define weekly targets by RM group');
assert.match(adminHtml, /ALLOWED_RM_GROUPS/, 'admin dashboard should explicitly limit the matrix to the 8 managed RM groups');
assert.doesNotMatch(adminHtml, /groupMap\.keys\(\)/, 'admin dashboard should not add unmanaged RM groups such as 198 to the matrix');
assert.match(adminHtml, /环金/, 'admin dashboard should expose the shortened 环金 customer segment');
assert.doesNotMatch(adminHtml, /資料品質提醒|組代號未填|組代號異常|會議已排除/, 'admin dashboard should not show data quality reminder chips');
assert.doesNotMatch(adminHtml, /行銷目標設定|活動類型|chart-type|renderTypeChart/, 'admin dashboard should remove target settings and activity type sections');
assert.doesNotMatch(adminHtml, /跟進提醒清單|followup-high|followup-regular|loadFollowUpList|逾期/, 'follow-up reminders should be merged into records and use 過期 wording');
assert.match(adminHtml, /follow-filter/, 'records section should include follow-up filters');
assert.match(adminHtml, /record-type-filter/, 'records section should include a record type filter');
assert.match(adminHtml, /<option value="meeting">會議紀錄<\/option>/, 'record type filter should offer meeting records');
assert.match(adminHtml, /type:\s*recordType/, 'record list requests should pass the selected record type');
assert.match(adminHtml, /excludeMeeting = false/, 'record list should include meetings unless a caller explicitly excludes them');
assert.match(adminHtml, /fetchRecordBatch\(\{ limit: 1000, excludeMeeting: true \}\)/, 'management report export should continue excluding meetings');
assert.match(adminHtml, /待跟進/, 'records section should include a pending follow-up filter');
assert.match(adminHtml, /過期/, 'records reminders should use 過期 wording');
assert.match(adminHtml, /latestReportByClient/, 'follow-up reminders should be based on each client latest report');
assert.match(adminHtml, /匯出管理報表 HTML/, 'admin dashboard should provide HTML management report export');
assert.match(adminHtml, /function exportManagementReportHTML\(/, 'admin dashboard should implement HTML management report export');
assert.match(adminHtml, /<option value="all" selected>全部資料<\/option>/, 'admin dashboard should default to all-time stats');
assert.match(adminHtml, /ADMIN_WEEKLY_VISITS = 1\.5/, 'weekly target should be fixed at 1.5 visits per person');
assert.match(adminHtml, /const range = 'all'/, 'admin dashboard should request all-time stats by default');
assert.match(adminHtml, /formatSegmentLine/, 'RM weekly cells should conditionally show only non-zero customer segment ratios');
assert.doesNotMatch(adminHtml, new RegExp(String.raw`\$\{count\} / \$\{target\}|\$\{count\}/\$\{groupTarget\}`), 'RM weekly cells should not show raw count over target text');
assert.match(adminHtml, /matrixStatusClass/, 'RM weekly matrix should have its own color threshold');
assert.match(adminHtml, /pct >= 60/, 'RM weekly matrix should mark 60 percent and above as green');
assert.match(adminHtml, /showCustomerTooltip/, 'RM weekly matrix cells should reveal customer names on hover or click');
assert.doesNotMatch(adminHtml, /slice\(0, 8\)/, 'RM weekly matrix should show all available weeks, not only the latest 8 weeks');
assert.match(adminHtml, /record-page-info/, 'records section should show page navigation');
assert.match(adminHtml, /renderRecordPageButtons/, 'records section should render numeric page buttons');
assert.match(adminHtml, /current-records-body/, 'records section should render current-month details separately');
assert.match(adminHtml, /history-records-body/, 'records section should render older details separately');
assert.match(adminHtml, /歷史明細/, 'records section should label older records as history details');
assert.match(adminHtml, /getCurrentMonthRange/, 'records section should use current month for the top detail list');
assert.match(adminHtml, /businessBadges/, 'records section should show business opportunity tags beside each company');
assert.match(adminHtml, /targetBusiness/, 'records business tags should come from each record targetBusiness field');
assert.match(adminHtml, /BIZ_COLORS/, 'records business tags should use a business color map');
assert.match(adminHtml, /TMU[\s\S]*#f59e0b/, 'TMU business tag should use yellow styling');
assert.match(adminHtml, /貿融[\s\S]*#f59e0b/, 'trade finance business tag should use yellow styling');
assert.match(adminHtml, /跨境轉介[\s\S]*#f97316/, 'cross-border business tag should use orange styling');
assert.match(adminHtml, /金流存款[\s\S]*#2563eb/, 'cash-management business tag should use blue styling');
assert.match(adminHtml, /bizStyle/, 'exported interactive report should reuse business tag colors');
assert.match(adminHtml, /segmentBadges/, 'records section should show customer segment tags beside each company');
assert.match(adminHtml, /SEGMENT_COLORS/, 'customer segment tags should use a segment color map');
assert.match(adminHtml, /环金[\s\S]*#db2777/, 'ring customer segment should use vivid pink styling');
assert.match(adminHtml, /環金型陸企|环金型陆企/, 'ring customer segment should display as a ring mainland-enterprise label');
assert.match(adminHtml, /function segmentLabel\(name,\s*companyType\)/, 'ring segment labels should consider company type');
assert.match(adminHtml, /isMainlandCompanyType\(companyType\)[\s\S]*環金型陸企/, 'only mainland companies with the ring segment should display as ring mainland enterprises');
assert.match(adminHtml, /segmentLabel\(s,\s*tmpl\.companyType\)/, 'record badges should pass company type into ring segment labeling');
assert.match(adminHtml, /fetchRecordBatch\(\{ limit: RECORDS_LIMIT, offset: recordsOffset, to: from, user, type: recordType \}\)/, 'history pagination should preserve the selected record type');
assert.doesNotMatch(adminHtml, /擊中領先指標|leading-hit-badge|chart-weekly|renderWeeklyChart\(statsData\.weeklyTrend\)/, 'leading indicator chart block should be removed from the dashboard');
assert.match(adminHtml, /<html lang="zh-CN">/, 'exported management report should use Simplified Chinese locale');
assert.match(adminHtml, /交互式管理报表/, 'exported management report should use Simplified Chinese wording');
assert.match(adminHtml, /body\{font-size:16px/, 'exported management report should use larger base font size');
assert.match(adminHtml, /weekly-matrix/, 'exported management report should give weekly matrix a dedicated readable style');
assert.match(adminHtml, /latestDailyDate/, 'exported recent 10 workday trend should anchor to the latest available data date');
assert.match(adminHtml, new RegExp(String.raw`['"]<['"] \+ ['"]\/script>['"]`), 'exported management report should emit a real closing script tag');
assert.doesNotMatch(adminHtml, new RegExp(String.raw`<\\\\\/script>`), 'exported management report should not leave an escaped script terminator in the saved HTML');
assert.match(adminHtml, /function sortRadarReport/, 'exported management report should support interactive radar sorting');
assert.match(adminHtml, /function filterReportRecords/, 'exported management report should support interactive record filtering');

assert.match(workerJs, /groupWeeklyMatrix/, 'stats API should return group weekly matrix data');
assert.match(workerJs, /radarScopes/, 'stats API should return scoped personal radar data');
assert.match(workerJs, /meeting_count/, 'scoped personal radar should include meeting counts');
assert.match(workerJs, /ring_count/, 'scoped personal radar should include ring-mainland visit counts');
assert.match(workerJs, /new_client_count/, 'scoped personal radar should include new-customer visit counts');
assert.match(workerJs, /customer_names/, 'group weekly matrix should include customer names for cell drilldown');
assert.match(workerJs, /visit_date >= '0000-01-01'[\s\S]*GROUP BY rm_group, week_key/, 'group weekly matrix should always use all-time weekly data');
assert.doesNotMatch(workerJs, /groupWeeklyMatrix[\s\S]{0,700}visit_date >= '\$\{since\}'/, 'group weekly matrix should not be constrained by the selected dashboard range');
assert.match(workerJs, /fromDate|toDate/, 'records API should support date-range filtering for current-month records');
assert.match(workerJs, /total/, 'records API should return total count for numeric pagination');
assert.match(workerJs, /excludeMeeting/, 'records API should support excluding meetings from paginated totals');
assert.match(workerJs, /recordType/, 'records API should support filtering by record type');
assert.match(workerJs, /where\.push\('type = \?'\)/, 'records API should apply record type filtering to rows and totals');
assert.doesNotMatch(workerJs, /dataQuality|unmanaged_rm_group|missing_rm_group|invalid_rm_group|excluded_meetings/, 'stats API should not return data quality reminder fields');
assert.match(workerJs, /json_extract\(.*customerSegments/, 'stats API should read customer segments from tmpl_json');
assert.match(workerJs, /json_extract\([^)]*tmpl_json[^)]*companyType[^)]*\)[\s\S]*IN \('陸資','陆资'\)/, 'ring statistics should require a mainland company type');
assert.match(workerJs, /type IN \('report','site'\)/, 'marketing stats should include reports and site visits while excluding meetings');
assert.match(workerJs, /ALLOWED_RM_GROUPS/, 'stats API should define the 8 managed RM groups');
assert.match(workerJs, /rm_group IN \(\$\{allowedGroupSql\}\)/, 'stats API should count only the managed RM groups');
assert.match(workerJs, /range\) === 'all'/, 'stats API should support all-time dashboard stats');
assert.match(workerJs, /const days\s+= isAllTime \? 0 : parseInt/, 'stats API should not parse all as a numeric day range');
assert.match(workerJs, /const prev\s+= isAllTime \? '0000-01-01' : daysAgo/, 'stats API should not compute invalid previous range dates for all-time stats');
assert.doesNotMatch(workerJs, /date\\('now', '-84 days'\\)|date\\('now', '-91 days'\\)/, 'weekly data should not be limited to recent 84 or 91 days');
