import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const adminHtml = readFileSync(new URL('../admin.html', import.meta.url), 'utf8');
const workerJs = readFileSync(new URL('../worker/index.js', import.meta.url), 'utf8');

assert.match(adminHtml, /週管理總覽/, 'admin dashboard should lead with weekly management overview');
assert.match(adminHtml, /RM 組動能逐週管理/, 'admin dashboard should include the RM group weekly momentum matrix');
assert.match(adminHtml, /近 10 工作日拜訪趨勢/, 'admin dashboard should preserve the recent 10 workday trend');
assert.match(adminHtml, /renderGroupWeeklyMatrix/, 'admin dashboard should render the group weekly matrix');
assert.match(adminHtml, /GROUP_TARGETS/, 'admin dashboard should define weekly targets by RM group');
assert.match(adminHtml, /ALLOWED_RM_GROUPS/, 'admin dashboard should explicitly limit the matrix to the 8 managed RM groups');
assert.doesNotMatch(adminHtml, /groupMap\.keys\(\)/, 'admin dashboard should not add unmanaged RM groups such as 198 to the matrix');
assert.match(adminHtml, /环金/, 'admin dashboard should expose the shortened 环金 customer segment');
assert.doesNotMatch(adminHtml, /資料品質提醒|組代號未填|組代號異常|會議已排除/, 'admin dashboard should not show data quality reminder chips');
assert.doesNotMatch(adminHtml, /行銷目標設定|活動類型|chart-type|renderTypeChart/, 'admin dashboard should remove target settings and activity type sections');
assert.doesNotMatch(adminHtml, /跟進提醒清單|followup-high|followup-regular|loadFollowUpList|逾期/, 'follow-up reminders should be merged into records and use 過期 wording');
assert.match(adminHtml, /follow-filter/, 'records section should include follow-up filters');
assert.match(adminHtml, /待跟進/, 'records section should include a pending follow-up filter');
assert.match(adminHtml, /過期/, 'records reminders should use 過期 wording');
assert.match(adminHtml, /latestReportByClient/, 'follow-up reminders should be based on each client latest report');
assert.match(adminHtml, /匯出管理報表 HTML/, 'admin dashboard should provide HTML management report export');
assert.match(adminHtml, /function exportManagementReportHTML\(/, 'admin dashboard should implement HTML management report export');
assert.match(adminHtml, /<option value="all" selected>全部資料<\/option>/, 'admin dashboard should default to all-time stats');
assert.match(adminHtml, /ADMIN_WEEKLY_VISITS = 1\.5/, 'weekly target should be fixed at 1.5 visits per person');
assert.match(adminHtml, /const range = 'all'/, 'admin dashboard should request all-time stats by default');
assert.match(adminHtml, /formatSegmentLine/, 'RM weekly cells should conditionally show only non-zero customer segment ratios');
assert.doesNotMatch(adminHtml, new RegExp(String.raw`\$\{count\} / \$\{target\}|\$\{count\}/\$\{groupTarget\}`), 'RM weekly cells should not show raw count over target text');
assert.match(adminHtml, /matrixStatusClass/, 'RM weekly matrix should have its own color threshold');
assert.match(adminHtml, /pct >= 60/, 'RM weekly matrix should mark 60 percent and above as green');
assert.match(adminHtml, /showCustomerTooltip/, 'RM weekly matrix cells should reveal customer names on hover or click');
assert.doesNotMatch(adminHtml, /slice\(0, 8\)/, 'RM weekly matrix should show all available weeks, not only the latest 8 weeks');
assert.match(adminHtml, /record-page-info/, 'records section should show page navigation');
assert.match(adminHtml, /getCurrentMonthRange/, 'records section should default to the current month');
assert.doesNotMatch(adminHtml, /擊中領先指標|leading-hit-badge|chart-weekly|renderWeeklyChart\(statsData\.weeklyTrend\)/, 'leading indicator chart block should be removed from the dashboard');

assert.match(workerJs, /groupWeeklyMatrix/, 'stats API should return group weekly matrix data');
assert.match(workerJs, /customer_names/, 'group weekly matrix should include customer names for cell drilldown');
assert.match(workerJs, /visit_date >= '0000-01-01'[\s\S]*GROUP BY rm_group, week_key/, 'group weekly matrix should always use all-time weekly data');
assert.doesNotMatch(workerJs, /groupWeeklyMatrix[\s\S]{0,700}visit_date >= '\$\{since\}'/, 'group weekly matrix should not be constrained by the selected dashboard range');
assert.match(workerJs, /fromDate|toDate/, 'records API should support date-range filtering for current-month records');
assert.doesNotMatch(workerJs, /dataQuality|unmanaged_rm_group|missing_rm_group|invalid_rm_group|excluded_meetings/, 'stats API should not return data quality reminder fields');
assert.match(workerJs, /json_extract\(.*customerSegments/, 'stats API should read customer segments from tmpl_json');
assert.match(workerJs, /type IN \('report','site'\)/, 'marketing stats should include reports and site visits while excluding meetings');
assert.match(workerJs, /ALLOWED_RM_GROUPS/, 'stats API should define the 8 managed RM groups');
assert.match(workerJs, /rm_group IN \(\$\{allowedGroupSql\}\)/, 'stats API should count only the managed RM groups');
assert.match(workerJs, /range\) === 'all'/, 'stats API should support all-time dashboard stats');
assert.match(workerJs, /const days\s+= isAllTime \? 0 : parseInt/, 'stats API should not parse all as a numeric day range');
assert.match(workerJs, /const prev\s+= isAllTime \? '0000-01-01' : daysAgo/, 'stats API should not compute invalid previous range dates for all-time stats');
assert.doesNotMatch(workerJs, /date\\('now', '-84 days'\\)|date\\('now', '-91 days'\\)/, 'weekly data should not be limited to recent 84 or 91 days');
